config/config/urls.py
from django.contrib import admin
from django.urls import path, include
#from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
	path('users/', include('users.urls', namespace='users')),
	path('accounts/', include('django.contrib.auth.urls')),
	path('', include('link_shortener.urls', namespace='link_shortener')),
	path('api-auth/',include('rest_framework.urls', namespace='rest_framework'))
]

config/link_shortener/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'link_shortener'

urlpatterns = [
    #path('', views.MainView.as_view()),
	path('', views.LinkShortenerFormView.as_view(), name='maine'),
	path('my_links', views.ShortLinkList.as_view()),
	path('<slug:pk>/update/', views.ShortLinkUpdate.as_view(), name='update'),
	path('<slug:pk>/delete/', views.ShortLinkDelete.as_view(), name='delete'),
	path('<slug:pk>/', views.ShortLinkDetail.as_view(), name='detail'),
]

config/users/urls.py
from django.urls import path, include

from .views import ProfileView
from .routers import router

app_name = 'users'
urlpatterns = [
	path('profile/', ProfileView.as_view(), name='profile'),
	path('api/',include(router.urls)),
]

config/link_shortener/models.py
from django.db import models
import uuid
from django.contrib.auth import get_user_model

class ShortLink(models.Model):
	id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
	long_link = models.URLField()
	short_link = models.CharField(max_length=6, unique=True)
	timestamp = models.DateTimeField(auto_now_add=True)
	user = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True)
	

# Create your models here.

config/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class UserPlan(models.Model):
	name = models.CharField(max_length=128)
	def __str__(self):
		return self.name

class User(AbstractUser):
	plan = models.ForeignKey('UserPlan',
		on_delete=models.SET_NULL,
		null=True,
		blank=True)
	def __str__(self):
		return f'{self.username}: {self.first_name}'
# Create your models here.

config/link_shortener/forms.py
from django import forms
from django.forms import ModelForm
from .models import ShortLink

class LinkForm(forms.Form):
	login_uri = forms.URLField()
	
class ShortLinkForm(ModelForm):

	
	
	
	class Meta:
		model = ShortLink
		fields = ('long_link',)
		
	
		

config/link_shortener/views.py
from django.shortcuts import render
from django.views import View
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic.edit import FormView
from .forms import LinkForm, ShortLinkForm
from .services import short_link_generator
from django.shortcuts import redirect
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.urls import reverse
from .models import ShortLink
from .services import get_long_link,check_recaptcha

class MainView(View):
	def get(self,request):
		return HttpResponse("Главная")

class LinkShortenerFormView(FormView):
	template_name = 'link_shortener/main.html'
	#form_class = LinkForm
	form_class = ShortLinkForm
	#success_url = '/my_links'
	def form_valid(self,form):
		if check_recaptcha(self.request.POST.get('g-recaptcha-response')):
			instance = form.save(commit=False)
			if self.request.user.is_authenticated:
				instance.user = self.request.user
			instance.short_link = short_link_generator()
			instance.save()
			#return redirect(self.get_success_url())
			return HttpResponseRedirect(reverse('link_shortener:detail',args=[instance.id]))
		else:
			return HttpResponse(status=403)
	def dispatch(self, request):
		short_link_url = self.request.GET.get('l')
		if short_link_url:
			long_link_url = get_long_link(short_link_url)
			if long_link_url:
				return redirect(long_link_url)
			else:
				return redirect('link_shortener:maine')
		return super(LinkShortenerFormView,self).dispatch(request)

class ShortLinkList(ListView):
	model = ShortLink
	paginate_by = 10
	
class ShortLinkUpdate(UpdateView):
	model = ShortLink
	fields = ['short_link']
	template_name_suffix = '_update_form'
	success_url = '/my_links'

class ShortLinkDelete(DeleteView):
	model = ShortLink
	success_url = '/my_links'	

class ShortLinkDetail(DetailView):
		model = ShortLink
# Create your views here.

config/users/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from rest_framework import viewsets

from .serializers import UserSerializer
from .models import User

class ProfileView(TemplateView):
	template_name = "users/profile.html"

class UserViewSet(viewsets.ModelViewSet):
	queryset = User.objects.filter(is_staff=False)
	serializer_class = UserSerializer

# Create your views here.

config/templates/base — копия.html
<!DOCTYPE html>
<html>
	<head>
		<title>{% block title %}
				{% endblock %}
		</title>
	</head>
	<body>
		{% block content %}
		{% endblock %}
	</body>
</html>

config/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
	<style>
		svg{
			width:32px;
			height:32px;
		}
	</style>
  </head>
  <body>
    {% block content %}
	{% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

config/templates/link_shortener/main.html
{% extends 'base.html' %}
{% block content %}
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
     <script>
       function onSubmit(token) {
         document.getElementById("main-form").submit();
       }
     </script>
<form id='main-form' method="POST">
	{% csrf_token %}
	{{form.as_p}}
	<button class="g-recaptcha" data-sitekey="6LeDCd4UAAAAAK_cVMoQw59a0slKidAM-RpS2vmT" data-callback='onSubmit'>OK</button>
	<!--
	<input type="Submit" value="OK">
	-->
</form>
{% endblock %}

config/templates/link_shortener/shortlink_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<form method="Post">
	{% csrf_token %}
	{{form.as_p}}
	<p>Are you sure you want to delete "{{ object }}"?</p>
	<input type="submit" value="ok">
</form>
{% endblock %}

config/templates/link_shortener/shortlink_detail.html
{% extends 'base.html' %}
{% block content %}
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">SHORT LINK</th>
      <th scope="col">LONG LINK</th>
    </tr>
  </thead>
  <tbody>
	<td>{{object.short_link}}</td>
	<td>{{object.long_link}}</td>
{% endblock %}

config/templates/link_shortener/shortlink_list.html
{% extends 'base.html' %}
{% block content %}
Количество ссылок_{{ object_list.count }}
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">ID</th>
      <th scope="col">SHORT LINK</th>
      <th scope="col">LONG LINK</th>
      <th scope="col">EDIT</th>
      <th scope="col">DEL</th>
    </tr>
  </thead>
  <tbody>
 
{% for link in object_list %}
		<tr>
		<th scope="row">{{ forloop.counter }}</th>
		<td>{{ link.id }}</td>
		<td>{{ link.short_link }}</td>
		<td>{{ link.long_link }}</td>
		<td><a href="{% url 'link_shortener:update' link.id %}"><svg xmlns='http://www.w3.org/2000/svg' width='512' height='512' viewBox='0 0 512 512'><title>Edit Short Link</title><polygon points='364.13 125.25 87 403 64 448 108.99 425 386.75 147.87 364.13 125.25' style='fill:none;stroke:#000;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px'/><path d='M420.69,68.69,398.07,91.31l22.62,22.63,22.62-22.63a16,16,0,0,0,0-22.62h0A16,16,0,0,0,420.69,68.69Z' style='fill:none;stroke:#000;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px'/></svg>
		</a>
		</td>
                <td><a href="{% url 'link_shortener:delete' link.id %}"><svg xmlns='http://www.w3.org/2000/svg' width='512' height='512' viewBox='0 0 512 512'><title>Del Edit Short Link</title><path d='M112,112l20,320c.95,18.49,14.4,32,32,32H348c17.67,0,30.87-13.51,32-32l20-320' style='fill:none;stroke:#000;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px'/><line x1='80' y1='112' x2='432' y2='112' style='stroke:#000;stroke-linecap:round;stroke-miterlimit:10;stroke-width:32px'/><path d='M192,112V72h0a23.93,23.93,0,0,1,24-24h80a23.93,23.93,0,0,1,24,24h0v40' style='fill:none;stroke:#000;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px'/><line x1='256' y1='176' x2='256' y2='400' style='fill:none;stroke:#000;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px'/><line x1='184' y1='176' x2='192' y2='400' style='fill:none;stroke:#000;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px'/><line x1='328' y1='176' x2='320' y2='400' style='fill:none;stroke:#000;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px'/></svg></a>
                </td>
		</tr>
{% endfor %}
	</tbody>
	</table>
{% include 'pagination.html' %}	
{% endblock %}

config/templates/link_shortener/shortlink_update_form.html
{% extends 'base.html' %}
{% block content %}
<form method="Post">
	{% csrf_token %}
	{{form.as_p}}
	<input type="submit" value="ok">
</form>
{% endblock %}

config/templates/pagination — копия.html
<nav aria-label="pagination">
    <ul class="pagination pagination-lg justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">prev</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">prev</a>
            </li>
        {% endif %}
        {% for page_num in paginator.page_range %}
            {% if page_obj.number == page_num %}
                <li class="page-item active"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link"
                                     href="?page={{ page_obj.next_page_number }}">next</a></li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link">next</a>
            </li>
        {% endif %}
    </ul>
</nav>

config/templates/pagination.html
<nav aria-label="pagination">
    <ul class="pagination pagination-lg justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">prev</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">prev</a>
            </li>
        {% endif %}
        {% for page_num in paginator.page_range %}
            {% if page_obj.number == page_num %}
                <li class="page-item active"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link"
                                     href="?page={{ page_obj.next_page_number }}">next</a></li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link">next</a>
            </li>
        {% endif %}
    </ul>
</nav>

config/templates/users/profile.html
{% extends 'base.html' %}
{% block content %}
	{% if user.is_authenticated %}
		<p>User name - {{user.username}}</p>
		<p>First name - {{user.first_name}}</p>
		<p>Last name - {{user.last_name}}</p>
		<p>Email - {{user.email}}</p>
		<p>Plan - {{user.plan}}</p>
	{% else %}
		<p>У вас нет прав</p>
	{% endif %}
{% endblock %}